apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2021-03-17T02-33-02Z
        args:
        - server
        - http://minio-{0...3}.minio-headless-svc.cicd.svc.cluster.local/export