version: "3"
services: 
  dev-docs:
    image: ${BASE_IMAGE_FULL}
    container_name: dev-docs
    volumes: 
      - ..:/workspace:cached
      - ../${DOCS_RELATIVE_PATH}:/${WOKRKING_PACKAGE_PATH}/${DOCS_RELATIVE_PATH}:cached
    ports:
      - ${VUEPRESS_DEV_PORT}:8080
    command: /bin/sh -c "while sleep 1000; do :; done"
  plantuml-server:
    image: ${PLANTUML_SERVER_IMAGE}
    container_name: plantuml-server