apiVersion: v1
kind: Service
metadata:
  name: minio-headless-svc
  labels:
    app: minio
spec:
  selector:
    app: minio
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: 9000
    targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  labels:
    app: minio
spec:
  selector:
    app: minio
  ports:
  - port: 9000
    targetPort: 9000
