apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  template:
    spec:
      containers:
        - name: argo-server
          image: argoproj/argocli:v3.0.0-rc8
          args:
            - server
            - --namespaced
            - --secure=false
            - --basehref=/cicd/argo/
          readinessProbe:
            httpGet:
              scheme: HTTP