apiVersion: v1
kind: Service
metadata:
  name: locust-master
spec:
  selector:
    app: locust-master
  ports:
  - name: web-ui
    port: 8089
    targetPort: 8089
  - name: master-bind
    port: 5557
    targetPort: 5557